# permissions for end users to view clusterwidenetworkpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterwidenetworkpolicy-viewer-role
rules:
- apiGroups:
  - firewall.metal-stack.io
  resources:
  - clusterwidenetworkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - firewall.metal-stack.io
  resources:
  - clusterwidenetworkpolicies/status
  verbs:
  - get
