---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: firewall-controller
  name: firewall-controller
  namespace: firewall-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firewall-controller
  template:
    metadata:
      labels:
        app: firewall-controller
    spec:
      containers:
      - image: metal-stack.io/firewall-controller
        imagePullPolicy: IfNotPresent
        name: firewall-controller
        securityContext:
          capabilities:
            add: 
            - "NET_ADMIN"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:firewall-controller
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - update
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal-stack.io
  resources:
  - networktraffics
  - networktraffics/status
  - networkids
  - firewalls
  - firewalls/status
  - clusterwidenetworkpolicies
  verbs:
  - list
  - get
  - update
  - create
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: firewall-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: firewall-controller
subjects:
- kind: User
  name: system:serviceaccount:firewall-controller:default
