---
apiVersion: v1
kind: Namespace
metadata:
  name: firewall
---
apiVersion: firewall.metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  namespace: firewall
  name: clusterwidenetworkpolicy-sample
spec:
  egress:
  - to:
    - cidr: 1.1.1.1/32
    - cidr: 1.0.0.1/32
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
  apiVersion: v1
  kind: Service
  metadata:
    name: s1
    namespace: firewall
  spec:
    type: LoadBalancer
    loadBalancerIP: 212.37.83.1
    loadBalancerSourceRanges:
    - 192.168.0.0/24
    - 192.168.2.0/24
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8063
    - name: test
      protocol: TCP
      port: 53
      targetPort: 8064
