name: Docker Image from master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olegtarasov/get-tag@v1
      id: tagName
    - name: Build the Docker images
      run: |
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        apt install -y --no-install-recommends nftables
        make test-all
        make docker-build
        make docker-push
