name: Docker Image from master

on:
  push:
    branches:
      - master

jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: olegtarasov/get-tag@v1
      id: tagName
    - name: Build the Docker images
      run: |
        sudo apt install -y --no-install-recommends nftables
        sudo make test-all clean
  build:
    needs: integration
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: olegtarasov/get-tag@v1
      id: tagName
    - name: Build the Docker images
      run: |
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        make docker-build
        make docker-push
