name: Docker Image from release tags

on:
  push:
    tags:
      - "v*"

jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: olegtarasov/get-tag@v1
      id: tagName
    - name: run integration tests
      run: |
        sudo apt install -y --no-install-recommends nftables
        sudo make test-all clean
  build:
    needs: integration
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Build the Docker images
      run: |
        export GITHUB_TAG_NAME=${GITHUB_REF##*/}
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        make docker-build
        make docker-push
